version: '3.8'
services:
  vosk_cpu_worker:
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 10
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /mnt/share/audio_call/saved_for_analysis/debug/wer/:/worker/audio/wer
      - /mnt/share/audio_call/PATH_TO_YOUR_FILES/:/worker/audio/stereo
      - /mnt/share/audio_master/PATH_TO_YOUR_FILES/:/worker/audio/mono
      - ./vosk_cpu_worker/id_garden:/worker/id_garden
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: vosk_cpu_worker
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=0
      - WORKERS_COUNT=10
      - SAVE_FOR_ANALYSIS=0
      - TRANSCRIBE_MAX_TRY_COUNT=100
      - TE_DOCKER_ADDRESS=
      - TZ=Europe/Moscow
      - POSTGRESQL_SERVER=
      - POSTGRESQL_PORT=
      - POSTGRESQL_LOGIN=
      - POSTGRESQL_PASSWORD=
      - TELEGRAM_CHAT=
      - TELEGRAM_BOT_TOKEN=
      - VOSK_SERVER_DEFAULT=
      - VOSK_SERVER_WORKER_0=

  vosk_queue:
    restart: on-failure[:2]
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /mnt/share/audio_call/PATH_TO_YOUR_FILES/:/app/audio/stereo
      - /mnt/share/audio_master/PATH_TO_YOUR_FILES/:/app/audio/mono
      - /mnt/share/audio_call/saved_for_analysis/:/app/audio/saved_for_analysis
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: vosk_queue
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - WORKERS_COUNT=10
      - TZ=Europe/Moscow
      - POSTGRESQL_SERVER=
      - POSTGRESQL_PORT=
      - POSTGRESQL_LOGIN=
      - POSTGRESQL_PASSWORD=
      - MYSQL_SERVER=
      - MYSQL_LOGIN=
      - MYSQL_PASSWORD=
      - TELEGRAM_CHAT=
      - TELEGRAM_BOT_TOKEN=
      - SAVE_FOR_ANALYSIS=0
  vosk_cleaner:
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: vosk_cleaner
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Europe/Moscow
      - POSTGRESQL_SERVER=
      - POSTGRESQL_PORT=
      - POSTGRESQL_LOGIN=
      - POSTGRESQL_PASSWORD=